# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 367)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.new_task_label = QtWidgets.QLabel(self.centralwidget)
        self.new_task_label.setGeometry(QtCore.QRect(10, 250, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_task_label.setFont(font)
        self.new_task_label.setObjectName("new_task_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 240, 511, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.save_task_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_task_button.setGeometry(QtCore.QRect(430, 310, 91, 31))
        self.save_task_button.setObjectName("save_task_button")
        self.current_task_table = QtWidgets.QTableWidget(self.centralwidget)
        self.current_task_table.setGeometry(QtCore.QRect(10, 10, 511, 231))
        self.current_task_table.setObjectName("current_task_table")
        self.current_task_table.setColumnCount(0)
        self.current_task_table.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 310, 201, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.task_timeout_label = QtWidgets.QLabel(self.layoutWidget)
        self.task_timeout_label.setObjectName("task_timeout_label")
        self.horizontalLayout_2.addWidget(self.task_timeout_label)
        self.task_timeout_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.task_timeout_comboBox.setObjectName("task_timeout_comboBox")
        self.task_timeout_comboBox.addItem("")
        self.task_timeout_comboBox.addItem("")
        self.task_timeout_comboBox.addItem("")
        self.task_timeout_comboBox.addItem("")
        self.task_timeout_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.task_timeout_comboBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 280, 511, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_task_name_label = QtWidgets.QLabel(self.layoutWidget1)
        self.new_task_name_label.setObjectName("new_task_name_label")
        self.horizontalLayout.addWidget(self.new_task_name_label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.task_timeout_comboBox.setCurrentIndex(3)
        self.save_task_button.clicked.connect(MainWindow.save_task_on_button_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_task_label.setText(_translate("MainWindow", "Новая задача"))
        self.save_task_button.setText(_translate("MainWindow", "Записать"))
        self.task_timeout_label.setText(_translate("MainWindow", "Контроль времени:"))
        self.task_timeout_comboBox.setItemText(0, _translate("MainWindow", "30 минут", "30"))
        self.task_timeout_comboBox.setItemText(1, _translate("MainWindow", "1 час", "60"))
        self.task_timeout_comboBox.setItemText(2, _translate("MainWindow", "2 часа", "120"))
        self.task_timeout_comboBox.setItemText(3, _translate("MainWindow", "4 часа", "240"))
        self.task_timeout_comboBox.setItemText(4, _translate("MainWindow", "1 день", "1440"))
        self.new_task_name_label.setText(_translate("MainWindow", "Что делаем:"))
